language: python
sudo: false
before_script:
  - pip install .
script: python example.py
branches:
  only:
    - master
notifications:
  recipients:
    - chrisl@luma-pictures.com
  email:
    on_success: change
    on_failure: always
